exclude: [config.rb, nginx.conf, node_modules, package.json, project.sublime-project, project.sublime-workspace, README.md, supervisor.conf]
markdown: rdiscount
highlighter: true
permalink: /:title
rdiscount:
  extensions: [smart]
